spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/batis
    username: test
    password: 1111
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mybatis_project.domain
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true